apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      name: outerport
      targetPort: db-postgres
      nodePort: 30002
      protocol: TCP
  selector:
    app: postgres