apiVersion: v1
kind: Service
metadata:
    name: redis-cart
spec:
    type: NodePort
    selector:
        app: redis-cart
    ports:
        - name: tcp-redis
          port: 6379
          targetPort: 6379
          nodePort: 30099
          protocol: TCP
